name: Build and Publish SiteMesh 3 Grails Plugin

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17 with cache
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'gradle'
      - name: Run build with Gradle Wrapper
        env:
          MAVEN_PUBLISH_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.GH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew test publish